language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=2.1.3

before_script:
  - git clone --depth 1 git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../chosen-cakephp plugins/Chosen
  - chmod -R 777 ../cakephp/app/tmp
  - set +H

script:
  - ./lib/Cake/Console/cake test Chosen View/Helper/ChosenHelper --stderr