language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=2.0.3

before_script:
  - mkdir ../cakephp
  - wget https://github.com/cakephp/cakephp/archive/2.0.6.tar.gz
  - tar -xzf 2.0.6.tar.gz -C ../ && cd ../cakephp-2.0.6
  - mysql -e 'CREATE DATABASE cakephp_test;'
  - cp -R ../chosen-cakephp plugins/Chosen
  - chmod -R 777 ../cakephp-2.0.6/app/tmp
  - set +H
  - echo "<?php
      class DATABASE_CONFIG {
      private \$identities = array(
        'mysql' => array(
          'datasource' => 'Database/Mysql',
          'host' => '0.0.0.0',
          'login' => 'travis'
        ),
        'pgsql' => array(
          'datasource' => 'Database/Postgres',
          'host' => '127.0.0.1',
          'login' => 'postgres',
          'database' => 'cakephp_test',
          'schema' => array(
            'default' => 'public',
            'test' => 'public'
          )
        )
      );
      public \$default = array(
        'persistent' => false,
        'host' => '',
        'login' => '',
        'password' => '',
        'database' => 'cakephp_test',
        'prefix' => ''
      );
      public \$test = array(
        'persistent' => false,
        'host' => '',
        'login' => '',
        'password' => '',
        'database' => 'cakephp_test',
        'prefix' => ''
      );
      public function __construct() {
        \$db = 'mysql';
        if (!empty(\$_SERVER['DB'])) {
          \$db = \$_SERVER['DB'];
        }
        foreach (array('default', 'test') as \$source) {
          \$config = array_merge(\$this->{\$source}, \$this->identities[\$db]);
          if (is_array(\$config['database'])) {
            \$config['database'] = \$config['database'][\$source];
          }
          if (!empty(\$config['schema']) && is_array(\$config['schema'])) {
            \$config['schema'] = \$config['schema'][\$source];
          }
          \$this->{\$source} = \$config;
        }
      }
      }" > ../cakephp-2.0.6/app/Config/database.php
script:
  - ./lib/Cake/Console/cake test Chosen View/Helper/ChosenHelper --stderr